---
title: "Pre-registration details"
date: "Last run: `r format(Sys.time(), '%F')`"
---

# Study Information

## Title 

TODO

## Authorship

- Suparna Chaudhry
- Marc Dotson
- Andrew Heiss

## Research Questions 

> Please list each research question included in this study.

- What makes donors donate?
- Structural factors - relationship with government - organizational level
- Organizational - 

- Individuals

TODO: Find that other conjoin article

## Hypotheses

> For each of the research questions listed in the previous section, provide one or multiple specific and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here.

- TODO
- TODO



EGAP - conjoint examples

Subgroups, like people who have donated a lot vs. not

TODO: Check distribution of donation frequency

Size of donation - separate models
Volunteering 
Political views
Prosocial views
Demographic stuff



---


# Sampling Plan

## Existing data

Registration prior to creation of data

## Explanation of existing data

We will not use any existing data.

## Data collection procedures

> Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that don’t include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

TODO

## Sample size

> Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis?

TODO

## Sample size rationale

> This could include a power analysis or an arbitrary constraint such as time, money, or personnel.

TODO

## Stopping rule

> If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

TODO


---


# Variables

## Manipulated variables

> Describe all variables you plan to manipulate and the levels or treatment arms of each variable. For observational studies and meta-analyses, simply state that this is not applicable.

TODO

## Measured variables

> Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

TODO

## Indices

> If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

TODO


---


# Design plan

## Study type

Experiment - A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.

## Blinding

For studies that involve human subjects, they will not know the treatment group to which they have been assigned.

## Study design

> Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies. 

TODO - conjoint design

## Randomization

> If you are doing a randomized study, how will you randomize, and at what level? 

TODO


---


# Analysis Plan

## Statistical models

> What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions that will be tested and remember that any test not included here must be noted as an exploratory test in your final article.

TODO

## Transformations

> If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process.

TODO

## Follow-up analyses

> If not specified previously, will you be conducting any confirmatory analyses to follow up on effects in your statistical model, such as subgroup analyses, pairwise or complex contrasts, or follow-up tests from interactions? Remember that any analyses not specified in this research plan must be noted as exploratory.

TODO

## Inference criteria

> What criteria will you use to make inferences? Please describe the information you’ll use (e.g. specify the p-values, Bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this? 

TODO

## Data exclusion

> How will you determine which data points or samples (if any) to exclude from your analyses? How will outliers be handled?

TODO

## Missing data

> How will you deal with incomplete or missing data?

TODO

## Exploratory analysis (optional)

> If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time. 

TODO


---


# Script (optional)

> Upload an analysis script with clear comments. This optional step is helpful in order to create a process that is completely transparent and increase the likelihood that your analysis can be replicated. We recommend that you run the code on a simulated dataset in order to check that it will run without errors.

MAYBE: This would be cool, but we'd need to create fake data in Qualtrics and run the analysis on that and make sure it all works before plugging in the real Qualtrics data (more time upfront)


---


# Other

> If there is any additional information that you feel needs to be included in your preregistration, please enter it here.

TODO
