---
title: "Results"
author: "Andrew Heiss, Marc Dotson, and Suparna Chaudhry"
---

See Chaudhry and Heiss (2019) preregistration for reference: <https://osf.io/dx973>

---


# Study Information

## Title 

Why Donors Donate: Disentangling Organizational and Structural Heuristics for International Philanthropy


## Authorship

- Suparna Chaudhry
- Marc Dotson
- Andrew Heiss


## Research Questions

> Please list each research question included in this study.

ANDREW TODO: Finish this section

We use a conjoint survey experiment to examine the impact of organizational and structural features of nongovernmental organizations (NGOs) on their donors’ decisions to engage in philanthropy. We explore three research questions in this study:

1. Donors rely on shortcuts, signals, and heuristics to determine the trustworthiness of NGOs, since seeking out complete information about an organization's deservingness and efficiency is costly and time-consuming. Previous research has found that structural characterists are common heuristics for donors. Organizational vs. structural heuristics

2. How those interact with individual characteristics

3. What is the optimal mix of attributes?

We are interested in whether the contentiousness of an NGO’s relationship with its host government influences donor decision making. Do donors care if nonprofits they care about are criticized by or kicked out of the countries they work in?

We are also interested in the effect of organizational characteristics on donor decision making. Do managerial practices (financial transparency and accountability systems), funding sources (private donations and government grants), and issue areas (emergency response, environmental issues, human rights, and refugee relief) also serve as heuristics that signal an organization’s deservingness to donors?

To test possible confounding and mediating effects, we also plan to see how donor characteristics influence the decision to donate, including political ideology, political knowledge, religious attendance, involvement in charitable activities, involvement in activism, and other demographic characteristics.


## Hypotheses

> For each of the research questions listed in the previous section, provide one or multiple specific and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here.

ANDREW TODO: write these

---


# Sampling Plan

## Existing data

Registration prior to creation of data


## Explanation of existing data

We will not use any existing data.


## Data collection procedures

> Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that don’t include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

Participants of the survey experiment will be recruited through Centiment, a commercial online provider of high quality nonprobability opt-in survey panels. Centiment ensures panel quality by actively recruiting representative samples of the US population and provides monetary incentives and rewards to participants.

To see how varying NGO characteristics influence the decision to donate, our sample will be representative of a population of people who are likely to donate to charity. We ask potential participants a screening question early in the survey (“Q2.5: How often do you donate to charity”). If a participant responds that they give to once every few years or never, they will be disqualified from the study and the survey will end early.

We will provide Centiment with a link to the survey, which is hosted by Qualtrics. Centiment will then distribute the link to their panel. Participants are compensated through Centiment’s internal reward system through cash, points, and other incentives. Centiment does not provide precise details of participant compensation. Centiment states that their compensation is “fair,” and the company’s business model encourages the company to find and maintain high quality panelists. We thus infer that the amount provided is fair and justified. Centiment users receive compensation from the company following the completion of the survey.


## Sample size

> Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis?

Our target sample size is 1,000 participants.


## Sample size rationale

> This could include a power analysis or an arbitrary constraint such as time, money, or personnel.

TODO: Add citation here maybe, or clarify the language so it's accurate

1,000 respondents constitutes a sufficient size for model estimation. A sample size of at least 500 respondents is typical for estimating a hierarchical Bayesian model based on conjoint data. We double this amount because we are interested in analyzing subpopulations of respondents, which requires a larger sample.


## Stopping rule

> If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

Centiment will monitor how many surveys are successfully completed and will solicit responses until our 1,000 target is met.


---


# Variables

## Manipulated variables

> Describe all variables you plan to manipulate and the levels or treatment arms of each variable. For observational studies and meta-analyses, simply state that this is not applicable.

We use a partial fractional factorial design with the following attributes:

**Organizations:**

- *Amnesty International*: A London-based non-governmental organization known for its focus on human rights.
- *Greenpeace*: An independent, nonprofit, global campaigning organization known for using non-violent, creative confrontation to expose global environmental problems and their causes.
- *Oxfam*: An international group known for providing help to poor countries and disaster areas, with a focus on helping create lasting solutions to the injustice of poverty. 
- *Red Cross*: An international organization known for caring for the wounded, sick, and homeless in wartime and following natural disasters.
 
**Issue areas:**

- *Emergency response*: Respond to situations that pose an immediate risk to health, life, property, or the environment.
- *Environment*: Protecting the natural world and the impact of human activity on its condition.
- *Human rights*: Protect the inalienable fundamental rights to which a person is inherently entitled simply because he or she is a human being.
- *Refugee relief*: Provide relief for those who have been forced to flee his or her country because of persecution, war or violence.  
 
**Organizational practices:**

- *Financial transparency*: Timely and reliable disclosure regarding donations and financial allocations. 
- *Accountability*: An obligation or willingness to accept responsibility or to account for one's actions.

**Funding sources:**

- *Funded primarily by many small private donations*: Funds by individuals who make small independent contributions.
- *Funded primarily by a handful of wealthy private donors*: Funds by wealthy individuals or families, who receive tax deductions for donations.
- *Funded primarily by government grants*: Non-repayable funds gifted by a government department.

**Relationship with host government:**

- *Friendly relationship with government*: Organization has a friendly relationship with its host government.
- *Criticized by government*: Organization faces public condemnation from the government.
- *Under government crackdown*: Host government has undertaken official action to limit or stop the organization. 

Participants are then presented with random combinations of these attributes and asked to select which of three hypothetical organizations they'd be willing to donate to.

This results in five manipulated variables:

- Organization
- Issue area
- Organizational practices
- Funding source
- Relationship with host government


## Measured variables

> Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

We collect one outcome measure, which we use as a dependent variable in our analysis. After displaying a table of randomized organizational attributes, we ask respondents "Imagine you are selecting an organization you will donate to and that each of the listed organizations exists. Which of the following organizations would you donate to?". Respondents are shown 12 of these sets, and their responses constitute our outcome.

We measure several other covariates that inform and predict an individual's choice of donating to a hypothetical organization (see survey instrument for complete question and response wording):

**Public affairs knowledge**

- *Q2.1*: How often do you follow national news?
- *Q2.2*: How often do you follow international news?
- *Q2.3*: Which mediums do you use to follow news?
- *Q2.4*: How often would you say you follow what's going on in government and public affairs?
- *Q5.7*: Have you ever traveled to a developing country? 

**Public affairs trust**

- *Q5.6*: Here is a 7-point scale on which you trust political institutions and the state. The scale is arranged from no trust (left) to complete trust (right). Where would you place yourself on this scale?

**Public affairs activity**

- *Q5.1*: Did you vote in the last election?

**Political ideology**

- *Q5.2*: 7-point scale on which the political views that people might hold are arranged from extremely liberal (left) to extremely conservative (right).

**Social ideology**

- *Q5.11*: Here is a 7-point scale of your prosocial views. The scale is arranged from equality (left) to altruism (right). Where would you place yourself on this scale?

**Charity trust**

- *Q2.7*: How important is it that you trust a charity before giving to it?
- *Q2.8*: How much do you trust charities?

**Charity activity**

- *Q2.5*: How often do you donate to charity?
- *Q2.6*: How much did you donate to charity last year?

**Volunteer activity**

- *Q2.9*: Have you volunteered in the past 12 months?
- *Q2.10*: How often do you volunteer?

**Activism activity**

- *Q5.4*: Historically, how involved have you been in activist causes?
- *Q5.5*: Historically, how involved has your family been in activist causes?

**Voluntary association membership**

- *Q5.3*: Here is a list of different types of voluntary organizations. For each organization, indicate whether you are an active member, an inactive member, or not a member of that type of organization:

    - Church or religious organization
    - Sport or recreational organization
    - Art, music, or educational organization
    - Labor union
    - Political party
    - Environmental organization
    - Professional association
    - Humanitarian or charitable organization
    - Consumer organization
    - Other organization

**Religiosity**

- *Q5.8*: How often do you attend religious or worship services, not including weddings and funerals?
- *Q5.9*: How important is religion in your life?
- *Q5.10*: What is your current religion, if any?

**Demographics**

- *Q5.12*: What is your gender?
- *Q5.13*: Are you now married, widowed, divorced, separated, or never married?
- *Q5.14*: What is the highest degree or level of school you have completed?
- *Q5.15*: What is your annual household income before taxes?
- *Q5.16*: Choose one or more races that you consider yourself to be:
- *Q5.17*: How old are you?
- *Q5.18*: What is your ZIP code?


## Indices

> If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

TODO: The paper at <https://osf.io/u43yg> uses Bayesian hierarchical stuff and they talk a lot about index stuff. I'm not familiar with the model, though, so I don't know what applies here.


---


# Design plan

## Study type

Experiment - A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.


## Blinding

For studies that involve human subjects, they will not know the treatment group to which they have been assigned.


## Study design

> Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies. 

TODO: Explain conjoint design

## Randomization

> If you are doing a randomized study, how will you randomize, and at what level? 

TODO: Explain randomization


---


# Analysis Plan

## Statistical models

> What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions that will be tested and remember that any test not included here must be noted as an exploratory test in your final article.

TODO: Explain statistical model

TODO: Make sure all this mathy stuff is right

TODO: Maybe specify priors?

Bayesian hierarchical multinomial logit

$$
\begin{aligned}
\beta &\sim \text{MVN}(Z \Gamma, \xi) \\
y &\sim \text{MNL}(X \beta, \varepsilon)
\end{aligned}
$$

where $y$ = choice to donate, $X$ = design matrix of attribute levels, $\beta$ = latent individual preferences, $Z$ = SOMETHING, $\Gamma$ = individual covariates, and $\varepsilon$ and $\xi$ = errors.


## Transformations

> If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process.

TODO: Are there any others we should collapse?

We collapse several of our variables into dichotomous and trichotomous versions, following this system:

*Q2.1*: How often do you follow national news? 

- Multiple times a day → At least once a day
- Every day → At least once a day
- Once a week → Once a week
- Hardly ever → Rarely (base case)
- Never → Rarely

*Q2.4*: How often would you say you follow what's going on in government and public affairs?

- Most of the time → Often
- Some of the time → Often
- Only now and then → Not often (base case)
- Hardly at all → Not often (base case)

*Q2.5*: How often do you donate to charity (with either cash or in-kind)?

- Once a week → At least once a month
- Once a month → At least once a month
- Once every three months → More than once a month, less than once a year
- Once every six months → More than once a month, less than once a year
- Once a year → More than once a month, less than once a year
- Once every few years → Rarely (base case)
- Never → Rarely

*Q2.10*: How often do you volunteer?

- Once a week → At least once a month
- Once a month → At least once a month
- Once every three months → More than once a month, less than once a year
- Once every six months → More than once a month, less than once a year
- Once a year → More than once a month, less than once a year
- Once every few years → Rarely (base case)
- Never → Rarely

*Q5.4*: Historically, how involved have you been in activist causes?

- Extremely involved → Involved
- Very involved → Involved
- Moderately involved → Involved
- Slightly involved → Not involved (base case)
- Never involved → Not involved

*Q5.5*: Historically, how involved has your family been in activist causes?

- Extremely involved → Involved
- Very involved → Involved
- Moderately involved → Involved
- Slightly involved → Not involved (base case)
- Never involved → Not involved

*Q5.8*: How often do you attend religious or worship services, not including weddings and funerals?

- More than once a week → At least once a month
- Once a week → At least once a month
- Once or twice a month → At least once a month
- A few times a year → Rarely (base case)
- Seldom → Rarely
- Never → Rarely
- Don't know → NULL

*Q5.9*: How important is religion in your life?

- Extremely important → Important
- Very important → Important
- Moderately important → Important
- Slightly important → Not important (base case)
- Not at all important → Not important

*Q5.15*: What is your annual household income before taxes?

- Less than $10,000 → More/less than median (base case = less than median)
- \$10,000 to \$19,999 → More/less than median
- \$20,000 to \$29,999 → More/less than median
- \$30,000 to \$39,999 → More/less than median
- \$40,000 to \$49,999 → More/less than median
- \$50,000 to \$59,999 → More/less than median
- \$60,000 to \$69,999 → More/less than median
- \$70,000 to \$79,999 → More/less than median
- \$80,000 to \$89,999 → More/less than median
- \$90,000 to \$99,999 → More/less than median
- \$100,000 to \$149,999 → More/less than median
- \$150,000 to \$199,999 → More/less than median
- \$200,000 to \$299,999 → More/less than median
- \$300,000 or more → More/less than median

*Q5.17*: How old are you?

- Under 18 → More/less than median (base case = less than median)
- 18 - 24 → More/less than median
- 25 - 34 → More/less than median
- 35 - 44 → More/less than median
- 45 - 54 → More/less than median
- 55 - 64 → More/less than median
- 65 - 74 → More/less than median
- 75 - 84 → More/less than median
- 85 or older → More/less than median


## Follow-up analyses

> If not specified previously, will you be conducting any confirmatory analyses to follow up on effects in your statistical model, such as subgroup analyses, pairwise or complex contrasts, or follow-up tests from interactions? Remember that any analyses not specified in this research plan must be noted as exploratory.

TODO: Do we do this?


## Inference criteria

> What criteria will you use to make inferences? Please describe the information you’ll use (e.g. specify the p-values, Bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this? 

NOTE: Here's a preregistration from another Bayesian hierarchical multinomial logit for reference: <https://osf.io/u43yg>

TODO: What criteria do we use?

Possibilities: 

- Market simulation based on the β - determines the optimal policies
- Or look at the posteriors of the βs
- β importance - we find most important attribute + most important levels inside 


## Data exclusion

> How will you determine which data points or samples (if any) to exclude from your analyses? How will outliers be handled?

We ask potential participants a screening question early in the survey ("Q2.5: How often do you donate to charity"). If a participant responds that they give to once every few years or never, they will be disqualified from the study and the survey will end early.

We include one question ("*Q2.11*: Please select blue from the following list:") to monitor respondent attention. In our analysis we will exclude respondents who fail this question.


## Missing data

> How will you deal with incomplete or missing data?

Because all survey questions are required, we do not anticipate issues with incomplete or missing data.


## Exploratory analysis (optional)

> If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time. 

TODO: NA?


---


# Script (optional)

> Upload an analysis script with clear comments. This optional step is helpful in order to create a process that is completely transparent and increase the likelihood that your analysis can be replicated. We recommend that you run the code on a simulated dataset in order to check that it will run without errors.

Nothing.

---


# Other

> If there is any additional information that you feel needs to be included in your preregistration, please enter it here.

Nothing.
