---
title: "Market Simulator"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r packages, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(flexdashboard)
library(plotly)
library(shiny)
library(here)
```

```{r load data}

# Beta's of everything. The only model we care about right now
public_political_social_charity_demo <- readRDS(here('analysis', 'output', 'posterior_draws', 'public_political_social_charity_demo.rds')) %>% 
  group_by(i, j) %>% 
  summarize(theta_mean = mean(Theta)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = j, values_from = theta_mean) %>% 
  select(-i)

# Persona Data from Market Simulator Workbook
persona_data <- readxl::read_xlsx(here('analysis', 'output', "persona_config.xlsx"))


#Levels (This is a guess):            Means:
#   1. Amnesty International          0.805
#   2. Greenpeace                     0.923
#   3. Oxfam                          0.620
#   4. Red Cross                      1.820
#   5. Environment                   -0.444
#   6. Human Rights                  -0.164
#   7. Refugee Relief                -0.582
#   8. Financially Transparent        1.080
#   9. Accountable                    1.130
#   10. Small wealthy donors         -0.376
#   11. Government Grants            -0.252
#   12. Criticized by Government       -0.663
#   13. Under Government Crackdown   -1.011


################### Org Reactive Element####################################

beta <- as.data.frame(matrix(rep(0), nrow = 13))

beta$levels = c("Amnesty International", "Greenpeace", "Oxfam", "Red Cross", "Environment", "Human rights", "Refugee relief", "Engages in transparency", "Engages in financial accountability","Handful of wealthy private donors", "Government Grants", "Criticized by government", "Under government crackdown")

# Org Reactive Element
df <- reactive({
  #Amnesty International
    beta$ai_value <- 0
    beta$ai_value[beta$levels == 'Amnesty International'] <- 1
    beta$ai_value[beta$levels %in% input$ai_issue] <- 1
    beta$ai_value[beta$levels %in% input$ai_fin_trans] <- 1
    beta$ai_value[beta$levels %in% input$ai_account] <- 1
    beta$ai_value[beta$levels %in% input$ai_funding] <- 1
    beta$ai_value[beta$levels %in% input$ai_gov_relat] <- 1
  #Greenpeace
    beta$gp_value <- 0
    beta$gp_value[beta$levels == 'Greenpeace'] <- 1
    beta$gp_value[beta$levels %in% input$gp_issue] <- 1
    beta$gp_value[beta$levels %in% input$gp_fin_trans] <- 1
    beta$gp_value[beta$levels %in% input$gp_account] <- 1
    beta$gp_value[beta$levels %in% input$gp_funding] <- 1
    beta$gp_value[beta$levels %in% input$gp_gov_relat] <- 1
  #Oxfam
    beta$ox_value <- 0
    beta$ox_value[beta$levels == 'Oxfam'] <- 1
    beta$ox_value[beta$levels %in% input$ox_issue] <- 1
    beta$ox_value[beta$levels %in% input$ox_fin_trans] <- 1
    beta$ox_value[beta$levels %in% input$ox_account] <- 1
    beta$ox_value[beta$levels %in% input$ox_funding] <- 1
    beta$ox_value[beta$levels %in% input$ox_gov_relat] <- 1
  #Redcross
    beta$rc_value <- 0
    beta$rc_value[beta$levels == 'Red Cross'] <- 1
    beta$rc_value[beta$levels %in% input$rc_issue] <- 1
    beta$rc_value[beta$levels %in% input$rc_fin_trans] <- 1
    beta$rc_value[beta$levels %in% input$rc_account] <- 1
    beta$rc_value[beta$levels %in% input$rc_funding] <- 1
    beta$rc_value[beta$levels %in% input$rc_gov_relat] <- 1
    beta
    
})

################### Persona Reactive Element####################################

# Persona beta levels -----

beta_persona <- as.data.frame(matrix(rep(0), nrow = 61))

beta_persona$levels = c("Intercept",
                        "Follow National News", 
                        "Follow International News",
                        "TV",
                        "Print",
                        "Online",
                        "Social Media",
                        "Radio",
                        "Email",
                        "Newsapp",
                        "Follow Government or Public Affairs", 
                        "No Travel to Developing Countries", 
                        "Political Preference", 
                        "Trust in Political Institutions",
                        "Others Should be Charitable",
                        "Worship Service Attendence",
                        "Religious Importance",
                        "Protestant",
                        "Christian Orthodox",
                        "Jewish",
                        "Muslim",
                        "Sikh",
                        "Hindu",
                        "Buddhist",
                        "Atheist",
                        "Other",
                        "Chartiy Trust Importance",
                        "Trust in Charity", 
                        "Donation Frequency", 
                        "Donation Amount",
                        "Volunteer 12 Months",
                        "Volunteer Frequence",
                        "Personal Activism",
                        "Family Activism",
                        "Religious Membership", 
                        "Sport or Recreational Membership", 
                        "Art, Music, or Educational Membership",
                        "Labor Union Membership",
                        "Political Party Membership",
                        "Environmental Organization Membership",
                        "Professional Association", 
                        "Humanitarian or Charity Membership",
                        "Consumer Organization Membership",
                        "Other Organization Membership",
                        "Female",
                        "Transgender",
                        "Prefer not to say",
                        "Other",
                        "Widowed",
                        "Divorced",
                        "Separated",
                        "Never Married",
                        "Education", 
                        "Income", 
                        "White", 
                        "Black", 
                        "American Indian", 
                        "Asian", 
                        "Pacific Islander", 
                        "Other", 
                        "Age")

# p reactive element ----


p <- reactive({
  
  #Persona 1
    beta_persona$p1_value <- 0

    beta_persona$p1_value[beta_persona$levels == 'Persona 1'] <- 1
    
    beta_persona$p1_value[beta_persona$levels %in% input$p1_national_news == '0'] <- 0
    beta_persona$p1_value[beta_persona$levels == '1'] <- 1
    beta_persona$p1_value[beta_persona$levels == '2'] <- 2
    beta_persona$p1_value[beta_persona$levels == '3'] <- 3
    beta_persona$p1_value[beta_persona$levels == '4'] <- 4
    beta_persona$p1_value[beta_persona$levels == '5'] <- 5
    beta_persona$p1_value[beta_persona$levels == '6'] <- 6
    beta_persona$p1_value[beta_persona$levels == '7'] <- 7
    
    beta_persona$p1_value[beta_persona$levels %in% input$p1_national_news] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_international_news] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_news_medium] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_follow_gov] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_travel_developing] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_political_pref] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_institution_trust] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_others_charitable] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_worship_attendence] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_religion_importance] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_religion] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_charity_importance] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_trust_in_charity] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_donation_frequency] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_donation_amount] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_volunteer_12] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_volunteer_frequency] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_personal_activism] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_family_activism] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_religious_member] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_sport_member] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_art_member] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_labor_member] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_political_member] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_environmental_member] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_professional_member] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_humanitarian_member] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_consumer_member] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_other_member] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_gender] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_marital_status] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_education] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_income] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_race] <- 1
    beta_persona$p1_value[beta_persona$levels %in% input$p1_age] <- 1
    
  #Persona 2
    beta_persona$p2_value <- 0

    beta_persona$p2_value[beta_persona$levels == 'Persona 2'] <- 1
    
    beta_persona$p2_value[beta_persona$levels == '0'] <- 0
    beta_persona$p2_value[beta_persona$levels == '1'] <- 1
    beta_persona$p2_value[beta_persona$levels == '2'] <- 2
    beta_persona$p2_value[beta_persona$levels == '3'] <- 3
    beta_persona$p2_value[beta_persona$levels == '4'] <- 4
    beta_persona$p2_value[beta_persona$levels == '5'] <- 5
    beta_persona$p2_value[beta_persona$levels == '6'] <- 6
    beta_persona$p2_value[beta_persona$levels == '7'] <- 7
    
    beta_persona$p2_value[beta_persona$levels %in% input$p2_national_news] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_international_news] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_news_medium] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_follow_gov] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_travel_developing] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_political_pref] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_institution_trust] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_others_charitable] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_worship_attendence] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_religion_importance] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_religion] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_charity_importance] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_trust_in_charity] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_donation_frequency] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_donation_amount] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_volunteer_12] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_volunteer_frequency] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_personal_activism] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_family_activism] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_religious_member] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_sport_member] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_art_member] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_labor_member] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_political_member] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_environmental_member] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_professional_member] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_humanitarian_member] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_consumer_member] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_other_member] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_gender] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_marital_status] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_education] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_income] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_race] <- 1
    beta_persona$p2_value[beta_persona$levels %in% input$p2_age] <- 1
    
  #Persona 3
    beta_persona$p3_value <- 0

    beta_persona$p3_value[beta_persona$levels == 'Persona 3'] <- 1

    beta_persona$p3_value[beta_persona$levels %in% input$p3_national_news] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_international_news] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_news_medium] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_follow_gov] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_travel_developing] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_political_pref] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_institution_trust] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_others_charitable] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_worship_attendence] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_religion_importance] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_religion] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_charity_importance] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_trust_in_charity] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_donation_frequency] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_donation_amount] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_volunteer_12] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_volunteer_frequency] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_personal_activism] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_family_activism] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_religious_member] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_sport_member] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_art_member] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_labor_member] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_political_member] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_environmental_member] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_professional_member] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_humanitarian_member] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_consumer_member] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_other_member] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_gender] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_marital_status] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_education] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_income] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_race] <- 1
    beta_persona$p3_value[beta_persona$levels %in% input$p3_age] <- 1
    beta_persona

})
```


```{r practice code}

#### this chunk is for testing code and making sure things work before adding it into the dashboard


# beta_persona_test <- as.data.frame(matrix(rep(0), nrow = 38))
# 
# beta_persona_test$levels = c("Persona 1", "Persona 2", "Persona 3", "Chartiy Importance", "Trust in Charity", "Donation Frequency", "Donation Amount", "Volunteer 12 Months", "Volunteer Frequence","Personal Activism", "Family Activism", "Religious Membership", "Sport or Recreational Membership", "Art, Music, or Educational Membership","Labor Union Membership", "Political Party Membership", "Environmental Organization Membership", "Professional Association", "Humanitarian or Charity Membership","Consumer Organization Membership", "Other Organization Membership", "Follow National News", "Follow International News", "News Medium","Follow Government or Public Affairs", "Travel to Developing Countries", "Political Preference", "Trust in Political Institutions", "Others Should be Charitable", "Worship Service Attendence", "Religious Importance", "Religion", "Gender", "Marital Status", "Education", "Income", "Race", "Age")
# 
# 
# 
# # Persona Reactive Element
# 
# beta_persona_test$p1 <- 1
# 
# beta_persona_test$p2 <- 2
# 
# beta_persona_test$p3 <- 3
#         
# persona1 <- persona_data[,2]
# 
# p_beta1 <- as.matrix(public_political_social_charity_demo) %*%   
#   
#   as.matrix(persona1) %*% beta_persona_test[,3]


  


```

```{r matrix multiplication, eval=FALSE, include=FALSE}
library(shiny)

beta <- data.frame(
  value = c(0,0,0),
  levels = c("Environment", "Human rights", "Refugee relief")
)

ui <- fluidPage(
  fluidRow(
    column(6,
      selectInput("ai_issue", 
                  label = "Select Issue Area:",
                  choices = beta$levels,
                  multiple = TRUE)
    ),
    column(6,
      tableOutput("data")
    )
  )
)

server = function(input, output) {

  df <- reactive({
    beta$value[beta$levels %in% input$ai_issue] <- 1
    beta
  })

  output$data <- renderTable({
    df()
  })
}
```

<!-- Persona Inputs  -->
<!-- ================================================= -->

<!-- ## Persona Inputs -->



```{r persona betas}

### Calculating the Persona betas ###

# Persona 1
persona1 <- persona_data[,2]

p_beta1 <- as.matrix(public_political_social_charity_demo) %*% as.matrix(persona1)

beta_test <- as.data.frame(matrix(rep(0), nrow = 13))

beta_test$levels = c("Amnesty International", "Greenpeace", "Oxfam", "Red Cross", "Environment", "Human rights", "Refugee relief", "Engages in transparency", "Engages in financial accountability","Handful of wealthy private donors", "Government Grants", "Criticized by government", "Under government crackdown")

beta_test$ai_issue <- 0
beta_test$ai_issue[4] <- 1
beta_test$ai_issue[8] <- 1
beta_test$ai_issue[9] <- 1


beta_test$gp_issue <- 0
beta_test$gp_issue[4] <- 1
beta_test$gp_issue[5] <- 1
beta_test$gp_issue[8] <- 1
beta_test$gp_issue[9] <- 1


beta_test$ox_issue <- 0
beta_test$ox_issue[4] <- 1
beta_test$ox_issue[6] <- 1
beta_test$ox_issue[8] <- 1
beta_test$ox_issue[9] <- 1

beta_test$rc_issue <- 0
beta_test$rc_issue[4] <- 1
beta_test$rc_issue[7] <- 1
beta_test$rc_issue[8] <- 1
beta_test$rc_issue[9] <- 1



  ai_exp_util1 <- round(exp(t(beta_test[, 3]) %*% as.matrix(p_beta1)),2)
  gp_exp_util1 <- round(exp(t(beta_test[, 4]) %*% as.matrix(p_beta1)),2)
  ox_exp_util1 <- round(exp(t(beta_test[, 5]) %*% as.matrix(p_beta1)),2)
  rc_exp_util1 <- round(exp(t(beta_test[, 6]) %*% as.matrix(p_beta1)),2)

  ai_rate1 <- round(100 * ai_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
  gp_rate1 <- round(100 * gp_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
  ox_rate1 <- round(100 * ox_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
  rc_rate1 <- round(100 * rc_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))


# Persona 2
persona2 <- persona_data[,3]

p_beta2 <- as.matrix(public_political_social_charity_demo) %*% as.matrix(persona2)



exp_util2 <- round(exp(t(beta_test[, 4]) %*% as.matrix(p_beta2)),2)


# Persona 3
persona3 <- persona_data[,4]

p_beta3 <- as.matrix(public_political_social_charity_demo) %*% as.matrix(persona3)


exp_util3 <- round(exp(t(beta_test[, 5]) %*% as.matrix(p_beta3)),2)

```

<!-- Main page Chart with All Personas -->

Market Share Per Persona
--------------------------------------

```{r plot all personas}

renderPlotly({
  org_choice = df()
  per_choice = p()
    
    p_beta1 <- as.matrix(public_political_social_charity_demo) %*% as.matrix(per_choice[,3])
#add step to matrix multiply the persona reactive element to the persona data and the public_political beta table.
  
  ai_exp_util1 <- round(exp(t(org_choice[, 3]) %*% as.matrix(p_beta1)),2)
  gp_exp_util1 <- round(exp(t(org_choice[, 4]) %*% as.matrix(p_beta1)),2)
  ox_exp_util1 <- round(exp(t(org_choice[, 5]) %*% as.matrix(p_beta1)),2)
  rc_exp_util1 <- round(exp(t(org_choice[, 6]) %*% as.matrix(p_beta1)),2)
  
  ai_rate1 <- round(100 * ai_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
  gp_rate1 <- round(100 * gp_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
  ox_rate1 <- round(100 * ox_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
  rc_rate1 <- round(100 * rc_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
  
    p_beta2 <- as.matrix(public_political_social_charity_demo) %*% as.matrix(per_choice[,4])
  
  ai_exp_util2 <- round(exp(t(org_choice[, 3]) %*% as.matrix(p_beta2)),2)
  gp_exp_util2 <- round(exp(t(org_choice[, 4]) %*% as.matrix(p_beta2)),2)
  ox_exp_util2 <- round(exp(t(org_choice[, 5]) %*% as.matrix(p_beta2)),2)
  rc_exp_util2 <- round(exp(t(org_choice[, 6]) %*% as.matrix(p_beta2)),2)
  
  ai_rate2 <- round(100 * ai_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
  gp_rate2 <- round(100 * gp_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
  ox_rate2 <- round(100 * ox_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
  rc_rate2 <- round(100 * rc_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
  
    p_beta3 <- as.matrix(public_political_social_charity_demo) %*% as.matrix(per_choice[,5])
  
  ai_exp_util3 <- round(exp(t(org_choice[, 3]) %*% as.matrix(p_beta3)),2)
  gp_exp_util3 <- round(exp(t(org_choice[, 4]) %*% as.matrix(p_beta3)),2)
  ox_exp_util3 <- round(exp(t(org_choice[, 5]) %*% as.matrix(p_beta3)),2)
  rc_exp_util3 <- round(exp(t(org_choice[, 6]) %*% as.matrix(p_beta3)),2)
  
  ai_rate3 <- round(100 * ai_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
  gp_rate3 <- round(100 * gp_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
  ox_rate3 <- round(100 * ox_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
  rc_rate3 <- round(100 * rc_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
  
  data <- c(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1, ai_rate1, gp_rate1, ox_rate1, rc_rate1, 
            ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2, ai_rate2, gp_rate2, ox_rate2, rc_rate2,
            ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3, ai_rate3, gp_rate3, ox_rate3, rc_rate3)
  
  
  df <- as.data.frame(matrix(data, 24, 1))
  
  df[,2] <- c("Amnesty International", "Greenpeace", "Oxfam", "Red Cross")
  df[,3] <- c(rep("Utility", 4), rep("Market Share", 4))
  df[,4] <- c(rep("Persona 1",8), rep("Persona 2", 8), rep("Persona 3", 8))
  colnames(df) <- c('Value', 'Organization', "Type", "Persona")
  
  ggplotly(df %>% filter(Type == "Market Share") %>% 
             ggplot(aes(y = Value, x = Organization, fill = Persona)) +
             geom_bar(position = "dodge", stat = "identity") +
             labs(x="") + 
             scale_fill_manual(values = c( "#FFC30B", "#3fad48", "#006633", "#660000")) +
             theme(legend.position = "none")
    )
})

```

<!-- Organizational Tabs -->

Organizations and Personas {.tabset .tabset-fade}
--------------------------------------------------
### Org 1

```{r plot ai plot}
# renderPlotly({
#   choice = df()
#   
#     persona1 = p_beta1 # Choose the persona
#   
#   ai_exp_util1 <- round(exp(t(choice[, 3]) %*% as.matrix(persona1)),2)
#   gp_exp_util1 <- round(exp(t(choice[, 4]) %*% as.matrix(persona1)),2)
#   ox_exp_util1 <- round(exp(t(choice[, 5]) %*% as.matrix(persona1)),2)
#   rc_exp_util1 <- round(exp(t(choice[, 6]) %*% as.matrix(persona1)),2)
#   
#   ai_rate1 <- round(100 * ai_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   gp_rate1 <- round(100 * gp_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   ox_rate1 <- round(100 * ox_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   rc_rate1 <- round(100 * rc_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   
#     persona2 = p_beta2 # Choose the persona
#   
#   ai_exp_util2 <- round(exp(t(choice[, 3]) %*% as.matrix(persona2)),2)
#   gp_exp_util2 <- round(exp(t(choice[, 4]) %*% as.matrix(persona2)),2)
#   ox_exp_util2 <- round(exp(t(choice[, 5]) %*% as.matrix(persona2)),2)
#   rc_exp_util2 <- round(exp(t(choice[, 6]) %*% as.matrix(persona2)),2)
#   
#   ai_rate2 <- round(100 * ai_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   gp_rate2 <- round(100 * gp_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   ox_rate2 <- round(100 * ox_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   rc_rate2 <- round(100 * rc_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   
#       persona3 = p_beta3 # Choose the persona
#   
#   ai_exp_util3 <- round(exp(t(choice[, 3]) %*% as.matrix(persona3)),2)
#   gp_exp_util3 <- round(exp(t(choice[, 4]) %*% as.matrix(persona3)),2)
#   ox_exp_util3 <- round(exp(t(choice[, 5]) %*% as.matrix(persona3)),2)
#   rc_exp_util3 <- round(exp(t(choice[, 6]) %*% as.matrix(persona3)),2)
#   
#   ai_rate3 <- round(100 * ai_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   gp_rate3 <- round(100 * gp_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   ox_rate3 <- round(100 * ox_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   rc_rate3 <- round(100 * rc_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   
#   data <- c(ai_exp_util1, ai_rate1, 
#             ai_exp_util2, ai_rate2,
#             ai_exp_util3, ai_rate3)
#   
#   
#   df <- as.data.frame(matrix(data, 6, 1))
#   
#   df[,2] <- c("Amnesty International")
#   df[,3] <- rep(c("Utility", "Market Share"), length.out = 6)
#   df[,4] <- c(rep("Persona 1", 2),rep("Persona 2", 2), rep("Persona 3", 2))
#   colnames(df) <- c('Value', 'Organization', "Type", "Persona")
#   
#   ggplotly(df %>% filter(Type == "Market Share") %>% 
#              ggplot(aes(y = Value, x = Organization, fill = Persona)) +
#              geom_bar(position = "dodge", stat = "identity") +
#              labs(x="") + 
#              scale_fill_manual(values = c( "#FFC30B", "#3fad48", "#006633", "#660000")) +
#              theme(legend.position = "none")
#     )
# })
```

```{r valuebox ai commented}
# renderValueBox({
#   choice = df()
#   
#   persona = p_beta1 # Choose the persona
#   
#   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2)
#   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2)
#   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2)
#   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2)
#   
#   ai_rate <- round(100 * ai_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util))
#   
#   valueBox(ai_rate,
#            color = "#FFC30B",
#            icon = "fa-percent")
# })
```

```{r ai org inputs}

# Some kind of Org Id that could select the organization you are looking at? Not sure how to make it change the label in the graph

selectInput("ai_issue", 
            label = "Select Issue Area:",
            choices = c("Emergency response",
                        "Environment",
                        "Human rights",
                        "Refugee relief"))

selectInput("ai_fin_trans",
            label = "Select Financial transparency:",
            choices = c("Doesn’t engage in transparency",
                        "Engages in transparency"))

selectInput("ai_account",
            label = "Select Financial Accountability:",
            choices = c("Doesn’t engage in financial accountability",
                        "Engages in financial accountability"))

selectInput("ai_funding",
            label = "Select Funding source:",
            choices = c("Many small private donations",
                        "Handful of wealthy private donors",
                        "Government Grants"))

selectInput("ai_gov_relat",
            label = "Select Relationship with host government",
            choices = c("Friendly relationship with government",
                        "Criticized by government", 
                        "Under government crackdown"))
```

```{r ai gauge}
renderGauge({
  choice = df()
  persona = p_beta1 # Choose the persona
   
  ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2)
  gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2)
  ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2)
  rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2)

  ai_rate <- round(100 * ai_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util))
  
  gauge(ai_rate,
        min = 0,
        max = 100,
        gaugeSectors(colors = "#FFC30B"),
        symbol = "%")
})

renderGauge({
  choice = df()
  persona = p_beta2 # Choose the persona
   
  ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2)
  gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2)
  ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2)
  rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2)

  ai_rate <- round(100 * ai_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util))
  
  gauge(ai_rate,
        min = 0,
        max = 100,
        gaugeSectors(colors = "#3fad48"),
        symbol = "%")
})

renderGauge({
  choice = df()
  persona = p_beta3 # Choose the persona
   
  ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2)
  gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2)
  ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2)
  rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2)

  ai_rate <- round(100 * ai_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util))
  
  gauge(ai_rate,
        min = 0,
        max = 100,
        gaugeSectors(colors = "#006633"),
        symbol = "%")
})
```

### Org 2

```{r plot gp plot}
# renderPlotly({
#   choice = df()
#   
#     persona1 = p_beta1 # Choose the persona
#   
#   ai_exp_util1 <- round(exp(t(choice[, 3]) %*% as.matrix(persona1)),2)
#   gp_exp_util1 <- round(exp(t(choice[, 4]) %*% as.matrix(persona1)),2)
#   ox_exp_util1 <- round(exp(t(choice[, 5]) %*% as.matrix(persona1)),2)
#   rc_exp_util1 <- round(exp(t(choice[, 6]) %*% as.matrix(persona1)),2)
#   
#   ai_rate1 <- round(100 * ai_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   gp_rate1 <- round(100 * gp_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   ox_rate1 <- round(100 * ox_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   rc_rate1 <- round(100 * rc_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   
#     persona2 = p_beta2 # Choose the persona
#   
#   ai_exp_util2 <- round(exp(t(choice[, 3]) %*% as.matrix(persona2)),2)
#   gp_exp_util2 <- round(exp(t(choice[, 4]) %*% as.matrix(persona2)),2)
#   ox_exp_util2 <- round(exp(t(choice[, 5]) %*% as.matrix(persona2)),2)
#   rc_exp_util2 <- round(exp(t(choice[, 6]) %*% as.matrix(persona2)),2)
#   
#   ai_rate2 <- round(100 * ai_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   gp_rate2 <- round(100 * gp_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   ox_rate2 <- round(100 * ox_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   rc_rate2 <- round(100 * rc_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   
#       persona3 = p_beta3 # Choose the persona
#   
#   ai_exp_util3 <- round(exp(t(choice[, 3]) %*% as.matrix(persona3)),2)
#   gp_exp_util3 <- round(exp(t(choice[, 4]) %*% as.matrix(persona3)),2)
#   ox_exp_util3 <- round(exp(t(choice[, 5]) %*% as.matrix(persona3)),2)
#   rc_exp_util3 <- round(exp(t(choice[, 6]) %*% as.matrix(persona3)),2)
#   
#   ai_rate3 <- round(100 * ai_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   gp_rate3 <- round(100 * gp_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   ox_rate3 <- round(100 * ox_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   rc_rate3 <- round(100 * rc_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   
#   data <- c(gp_exp_util1, gp_rate1, 
#             gp_exp_util2, gp_rate2,
#             gp_exp_util3, gp_rate3)
#   
#   
#   df <- as.data.frame(matrix(data, 6, 1))
#   
#   df[,2] <- c("Greenpeace")
#   df[,3] <- rep(c("Utility", "Market Share"), length.out = 6)
#   df[,4] <- c(rep("Persona 1", 2),rep("Persona 2", 2), rep("Persona 3", 2))
#   colnames(df) <- c('Value', 'Organization', "Type", "Persona")
#   
#   ggplotly(df %>% filter(Type == "Market Share") %>% 
#              ggplot(aes(y = Value, x = Organization, fill = Persona)) +
#              geom_bar(position = "dodge", stat = "identity") +
#              labs(x="") + 
#              scale_fill_manual(values = c( "#FFC30B", "#3fad48", "#006633", "#660000")) +
#              theme(legend.position = "none")
#     )
# })
```

```{r valuebox gp commented}
# renderValueBox({
#   choice = df()
#   persona = p_beta1 # Choose the persona
#   
#   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2)
#   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2)
#   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2)
#   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2)
#   
#   gp_rate <- round(100 * gp_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util))
#   
#   valueBox(gp_rate,
#            color = "#3fad48",
#            icon = "fa-percent")
# })
```

```{r gp org inputs}
selectInput("gp_issue", 
            label = "Select Issue Area:",
            choices = c("Emergency response",
                        "Environment",
                        "Human rights",
                        "Refugee relief"))

selectInput("gp_fin_trans",
            label = "Select Financial transparency:",
            choices = c("Doesn’t engage in transparency",
                        "Engages in transparency"))

selectInput("gp_account",
            label = "Select Financial Accountability:",
            choices = c("Doesn’t engage in accountability",
                        "Engages in financial accountability"))

selectInput("gp_funding",
            label = "Select Funding source:",
            choices = c("Many small private donations",
                        "Handful of wealthy private donors",
                        "Government Grants"))

selectInput("gp_gov_relat",
            label = "Select Relationship with host government",
            choices = c("Friendly relationship with government",
                        "Criticized by government", 
                        "Under government crackdown"))
```

```{r gp gauge}
renderGauge({
  choice = df()
  persona = p_beta1 # Choose the persona
   
  ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2)
  gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2)
  ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2)
  rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2)

  gp_rate <- round(100 * gp_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util))
  
  gauge(gp_rate,
        min = 0,
        max = 100,
        gaugeSectors(colors = "#3fad48"),
        symbol = "%")
})
```

### Org 3

```{r plot ox plot}
# renderPlotly({
#   choice = df()
#   
#     persona1 = p_beta1 # Choose the persona
#   
#   ai_exp_util1 <- round(exp(t(choice[, 3]) %*% as.matrix(persona1)),2)
#   gp_exp_util1 <- round(exp(t(choice[, 4]) %*% as.matrix(persona1)),2)
#   ox_exp_util1 <- round(exp(t(choice[, 5]) %*% as.matrix(persona1)),2)
#   rc_exp_util1 <- round(exp(t(choice[, 6]) %*% as.matrix(persona1)),2)
#   
#   ai_rate1 <- round(100 * ai_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   gp_rate1 <- round(100 * gp_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   ox_rate1 <- round(100 * ox_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   rc_rate1 <- round(100 * rc_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   
#     persona2 = p_beta2 # Choose the persona
#   
#   ai_exp_util2 <- round(exp(t(choice[, 3]) %*% as.matrix(persona2)),2)
#   gp_exp_util2 <- round(exp(t(choice[, 4]) %*% as.matrix(persona2)),2)
#   ox_exp_util2 <- round(exp(t(choice[, 5]) %*% as.matrix(persona2)),2)
#   rc_exp_util2 <- round(exp(t(choice[, 6]) %*% as.matrix(persona2)),2)
#   
#   ai_rate2 <- round(100 * ai_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   gp_rate2 <- round(100 * gp_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   ox_rate2 <- round(100 * ox_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   rc_rate2 <- round(100 * rc_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   
#       persona3 = p_beta3 # Choose the persona
#   
#   ai_exp_util3 <- round(exp(t(choice[, 3]) %*% as.matrix(persona3)),2)
#   gp_exp_util3 <- round(exp(t(choice[, 4]) %*% as.matrix(persona3)),2)
#   ox_exp_util3 <- round(exp(t(choice[, 5]) %*% as.matrix(persona3)),2)
#   rc_exp_util3 <- round(exp(t(choice[, 6]) %*% as.matrix(persona3)),2)
#   
#   ai_rate3 <- round(100 * ai_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   gp_rate3 <- round(100 * gp_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   ox_rate3 <- round(100 * ox_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   rc_rate3 <- round(100 * rc_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   
#   data <- c(ox_exp_util1, ox_rate1, 
#             ox_exp_util2, ox_rate2,
#             ox_exp_util3, ox_rate3)
#   
#   
#   df <- as.data.frame(matrix(data, 6, 1))
#   
#   df[,2] <- c("Oxfam")
#   df[,3] <- rep(c("Utility", "Market Share"), length.out = 6)
#   df[,4] <- c(rep("Persona 1", 2),rep("Persona 2", 2), rep("Persona 3", 2))
#   colnames(df) <- c('Value', 'Organization', "Type", "Persona")
#   
#   ggplotly(df %>% filter(Type == "Market Share") %>% 
#              ggplot(aes(y = Value, x = Organization, fill = Persona)) +
#              geom_bar(position = "dodge", stat = "identity") +
#              labs(x="") + 
#              scale_fill_manual(values = c( "#FFC30B", "#3fad48", "#006633", "#660000")) +
#              theme(legend.position = "none")
#     )
# })
```

```{r valuebox ox commented}
# renderValueBox({
#   choice = df()
#   
#   persona = p_beta1 # Choose the persona
#   
#   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2)
#   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2)
#   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2)
#   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2)
#   
#   ox_rate <- round(100 * ox_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util))
#   
#   valueBox(ox_rate,
#            color = "#006633",
#            icon = "fa-percent")
# })
```

```{r ox org inputs}
selectInput("ox_issue", 
            label = "Select Issue Area:",
            choices = c("Emergency response",
                        "Environment",
                        "Human rights",
                        "Refugee relief"))

selectInput("ox_fin_trans",
            label = "Select Financial transparency:",
            choices = c("Doesn’t engage in transparency",
                        "Engages in transparency"))

selectInput("ox_account",
            label = "Select Financial Accountability:",
            choices = c("Doesn’t engage in accountability",
                        "Engages in financial accountability"))

selectInput("ox_funding",
            label = "Select Funding source:",
            choices = c("Many small private donations",
                        "Handful of wealthy private donors",
                        "Government Grants"))

selectInput("ox_gov_relat",
            label = "Select Relationship with host government",
            choices = c("Friendly relationship with government",
                        "Criticized by government", 
                        "Under government crackdown"))
```

```{r ox gauge}
renderGauge({
  choice = df()
  persona = p_beta1 # Choose the persona
   
  ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2)
  gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2)
  ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2)
  rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2)

  ox_rate <- round(100 * ox_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util))
  
  gauge(ox_rate,
        min = 0,
        max = 100,
        gaugeSectors(colors = "#006633"),
        symbol = "%")
})
```

### Org 4

```{r plot rc plot}
# renderPlotly({
#   choice = df()
#   
#     persona1 = p_beta1 # Choose the persona
#   
#   ai_exp_util1 <- round(exp(t(choice[, 3]) %*% as.matrix(persona1)),2)
#   gp_exp_util1 <- round(exp(t(choice[, 4]) %*% as.matrix(persona1)),2)
#   ox_exp_util1 <- round(exp(t(choice[, 5]) %*% as.matrix(persona1)),2)
#   rc_exp_util1 <- round(exp(t(choice[, 6]) %*% as.matrix(persona1)),2)
#   
#   ai_rate1 <- round(100 * ai_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   gp_rate1 <- round(100 * gp_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   ox_rate1 <- round(100 * ox_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   rc_rate1 <- round(100 * rc_exp_util1/sum(ai_exp_util1, gp_exp_util1, ox_exp_util1, rc_exp_util1))
#   
#     persona2 = p_beta2 # Choose the persona
#   
#   ai_exp_util2 <- round(exp(t(choice[, 3]) %*% as.matrix(persona2)),2)
#   gp_exp_util2 <- round(exp(t(choice[, 4]) %*% as.matrix(persona2)),2)
#   ox_exp_util2 <- round(exp(t(choice[, 5]) %*% as.matrix(persona2)),2)
#   rc_exp_util2 <- round(exp(t(choice[, 6]) %*% as.matrix(persona2)),2)
#   
#   ai_rate2 <- round(100 * ai_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   gp_rate2 <- round(100 * gp_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   ox_rate2 <- round(100 * ox_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   rc_rate2 <- round(100 * rc_exp_util2/sum(ai_exp_util2, gp_exp_util2, ox_exp_util2, rc_exp_util2))
#   
#       persona3 = p_beta3 # Choose the persona
#   
#   ai_exp_util3 <- round(exp(t(choice[, 3]) %*% as.matrix(persona3)),2)
#   gp_exp_util3 <- round(exp(t(choice[, 4]) %*% as.matrix(persona3)),2)
#   ox_exp_util3 <- round(exp(t(choice[, 5]) %*% as.matrix(persona3)),2)
#   rc_exp_util3 <- round(exp(t(choice[, 6]) %*% as.matrix(persona3)),2)
#   
#   ai_rate3 <- round(100 * ai_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   gp_rate3 <- round(100 * gp_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   ox_rate3 <- round(100 * ox_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   rc_rate3 <- round(100 * rc_exp_util3/sum(ai_exp_util3, gp_exp_util3, ox_exp_util3, rc_exp_util3))
#   
#   data <- c(rc_exp_util1, rc_rate1, 
#             rc_exp_util2, rc_rate2,
#             rc_exp_util3, rc_rate3)
#   
#   
#   df <- as.data.frame(matrix(data, 6, 1))
#   
#   df[,2] <- c("Red Cross")
#   df[,3] <- rep(c("Utility", "Market Share"), length.out = 6)
#   df[,4] <- c(rep("Persona 1", 2),rep("Persona 2", 2), rep("Persona 3", 2))
#   colnames(df) <- c('Value', 'Organization', "Type", "Persona")
#   
#   ggplotly(df %>% filter(Type == "Market Share") %>% 
#              ggplot(aes(y = Value, x = Organization, fill = Persona)) +
#              geom_bar(position = "dodge", stat = "identity") +
#              labs(x="") + 
#              scale_fill_manual(values = c( "#FFC30B", "#3fad48", "#006633", "#660000")) +
#              theme(legend.position = "none")
#     )
# })
```

```{r valuebox rc commented}
# renderValueBox({
#   choice = df()
#   
#   persona = p_beta1 # Choose the persona
#    
#   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2)
#   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2)
#   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2)
#   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2)
#   
#   rc_rate <- round(100 * rc_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util))
#   
#   valueBox(rc_rate,
#            color = "#660000",
#            icon = "fa-percent")
# })
```

```{r rc org inputs}
selectInput("rc_issue", 
            label = "Select Issue Area:",
            choices = c("Emergency response",
                        "Environment",
                        "Human rights",
                        "Refugee relief"))

selectInput("rc_fin_trans",
            label = "Select Financial transparency:",
            choices = c("Doesn’t engage in transparency",
                        "Engages in transparency"))

selectInput("rc_account",
            label = "Select Financial Accountability:",
            choices = c("Doesn’t engage in accountability",
                        "Engages in financial accountability"))

selectInput("rc_funding",
            label = "Select Funding source:",
            choices = c("Many small private donations",
                        "Handful of wealthy private donors",
                        "Government Grants"))

selectInput("rc_gov_relat",
            label = "Select Relationship with host government",
            choices = c("Friendly relationship with government",
                        "Criticized by government", 
                        "Under government crackdown"))
```

```{r rc gauge}
renderGauge({
  choice = df()
  persona = p_beta1 # Choose the persona
   
  ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2)
  gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2)
  ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2)
  rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2)

  rc_rate <- round(100 * rc_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util))
  
  gauge(rc_rate,
        min = 0,
        max = 100,
        gaugeSectors(colors = "#660000"),
        symbol = "%")
})
```

### Persona 1

```{r persona 1 inputs}


# selectInput("model_choice",
#             label = "Select Model:",
#             choices = c("public_political_social_charity_demo"))

selectInput("p1_national_news",
         label = "Follow national news:",
         choices = c('Multiple times a day' = "1",
                     'Every day' = "2",
                     "Once a week" = "3",
                     "Hardly ever" = "4",
                     "Never" = "5"),
         width = "200px")


selectInput("p1_international_news",
         label = "Follow international news:",
         choices = c('Always',
                     "Sometimes",
                     "Never"))


selectInput("p1_news_medium",
         label = "Medium to follow news:",
         choices = c('TV',
                     'Print',
                     "Online",
                     "Social Media",
                     "Radio",
                     "Email newsletters",
                     "News app"),
         multiple = TRUE)


selectInput("p1_follow_gov",
         label = "Follow government & public affairs:",
         choices = c('Most of the time',
                     'Some of the time',
                     "Only now and then",
                     "Hardly at all"))


selectInput("p1_travel_developing",
         label = "Travel to developing country:",
         choices = c('Yes', 'No'))



selectInput("p1_political_pref",
         label = "Political views from liberal to conservative:",
         choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p1_institution_trust",
         label = "Political institution trust from none to complete:",
         choices = c("0", '1', '2', '3','4','5','6','7'))



selectInput("p1_others_charitable",
         label = "People should be more charitable:",
         choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p1_worship_attendance",
         label = "Worship service attendance:",
         choices = c('Multiple times a week',
                     'Once a week',
                     "Once a month",
                     "Once a year",
                     "Never"))


selectInput("p1_religion_importance",
         label = "Importance of religion:",
         choices = c('Extremely important',
                     'Very important',
                     'Moderately important',
                     'Slightly important',
                     'Not at all important'))


selectInput("p1_religion",
         label = "Religion:",
         choices = c('Catholic',
                     'Protestant',
                     'Christian Orthodox',
                     'Jewish',
                     'Muslim',
                     'Sikh',
                     'Hindu',
                     'Buddhist',
                     'Atheist',
                     'Other'))



selectInput("p1_national_news",
         label = "Follow national news:",
         choices = c('Multiple times a day',
                     'Every day',
                     "Once a week",
                     "Hardly ever",
                     "Never"))


selectInput("p1_international_news",
         label = "Follow international news:",
         choices = c('Always',
                     "Sometimes",
                     "Never"))


selectInput("p1_news_medium",
         label = "Medium to follow news:",
         choices = c('TV',
                     'Print',
                     "Online",
                     "Social Media",
                     "Radio",
                     "Email newsletters",
                     "News app"))


selectInput("p1_follow_gov",
         label = "Follow government & public affairs:",
         choices = c('Most of the time',
                     'Some of the time',
                     "Only now and then",
                     "Hardly at all"))


selectInput("p1_travel_developing",
         label = "Travel to developing country:",
         choices = c('Yes', 'No'))



selectInput("p1_political_pref",
         label = "Political views from liberal to conservative:",
         choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p1_institution_trust",
         label = "Political institution trust from none to complete:",
         choices = c("0", '1', '2', '3','4','5','6','7'))



selectInput("p1_others_charitable",
         label = "People should be more charitable:",
         choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p1_worship_attendance",
         label = "Worship service attendance:",
         choices = c('Multiple times a week',
                     'Once a week',
                     "Once a month",
                     "Once a year",
                     "Never"))


selectInput("p1_religion_importance",
         label = "Importance of religion:",
         choices = c('Extremely important',
                     'Very important',
                     'Moderately important',
                     'Slightly important',
                     'Not at all important'))


selectInput("p1_religion",
         label = "Religion:",
         choices = c('Catholic',
                     'Protestant',
                     'Christian Orthodox',
                     'Jewish',
                     'Muslim',
                     'Sikh',
                     'Hindu',
                     'Buddhist',
                     'Atheist',
                     'Other'))

selectInput("p1_charity_importance",
          label = "Charity Importance:",
          choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p1_trust_in_charity",
            label = "Charity Trust:",
            choices = c("0", '1', '2', '3','4','5','6','7'))



selectInput("p1_donation_frequency",
         label = "Donation Frequency:",
         choices = c('Once a week',
                     'Once a Month',
                     'Once every three months',
                     'Once every six months',
                     'Once a year',
                     'Once every few years',
                     'Never'))



selectInput("p1_donation_amount",
         label = "Donation Amount:",
         choices = c("$1-$49",
                     '$50-$99',
                     '$100-$499',
                     '$500-$999',
                     '$1,000-$4,999',
                     '$5,000-$9,999',
                     '$10,000+'))


selectInput("p1_volunteer_12",
         label = "Volunteered in last 12 Months:",
         choices = c("Yes", "No"))



selectInput("p1_volunteer_frequency",
         label = "Volunteer Frequency:",
         choices = c('Once a week',
                     'Once a Month',
                     'Once every three months',
                     'Once every six months',
                     'Once a year',
                     'Once every few years',
                     'Never'))


selectInput("p1_personal_activism",
         label = "Personal Activism:",
         choices = c('Extremely involved',
                     'Very involved',
                     'Moderately involved',
                     'Slightly involved',
                     'Never involved'))


selectInput("p1_family_activism",
         label = "Family Activism:",
         choices = c('Extremely involved',
                     'Very involved',
                     'Moderately involved',
                     'Slightly involved',
                     'Never involved'))


selectInput("p1_religious_member",
         label = "Church Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p1_sport_member",
         label = "Sport or Recreational Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p1_art_member",
         label = "Art, Music, or Educational Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p1_labor_member",
         label = "Labor Union Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p1_political_member",
         label = "Political Party Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p1_environmental_member",
         label = "Enviornmental Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p1_professional_member",
         label = "Professional Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p1_humanitarian_member",
         label = "Humanitarian Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p1_consumer_member",
         label = "Consumer Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))



selectInput("p1_other_member",
         label = "Other Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p1_gender",
         label = "Gender:",
         choices = c("Male",
                     "Female",
                     "Transgender",
                     "Prefer not to say",
                     "Other"))


selectInput("p1_marital_status",
         label = "Marital Status:",
         choices = c("Married",
                     "Widowed",
                     "Divorced",
                     "Separated",
                     "Never married"))


selectInput("p1_education",
         label = "Education:",
         choices = c("Less than high school",
                     "High school",
                     "Some college",
                     "2 year degree",
                     "4 year degree",
                     "Graduate degree",
                     "Doctorate"))

selectInput("p1_income",
         label = "Income:",
         choices = c('Less than $10,000',
                     '$10,000 to $19,999',
                     '$20,000 to $29,999',
                     '$30,000 to $39,999',
                     '$40,000 to $49,999',
                     '$50,000 to $59,999',
                     '$60,000 to $69,999',
                     '$70,000 to $79,999',
                     '$80,000 to $89,999',
                     '$90,000 to $99,999',
                     '$100,000 to $149,999',
                     '$150,000 to $199,999',
                     '$200,000 to $299,999',
                     '$300,000 or more'))



selectInput("p1_race",
         label = "Race(s):",
         choices = c('White',
                     'Black or African American',
                     'American Indian or Alaska Native',
                     'Asian',
                     'Native Hawaiian or Pacific Islander',
                     'Other'),
         multiple = TRUE)


selectInput("p1_age",
         label = "Age:",
         choices = c('Under 18',
                     '18 - 24',
                     '25 - 34',
                     '35 - 44',
                     '45 - 54',
                     '55 - 64',
                     '65 - 74',
                     '75 - 84',
                     '85 or older'))


```

### Persona 2

```{r persona 2 inputs}


# selectInput("model_choice",
#             label = "Select Model:",
#             choices = c("public_political_social_charity_demo"))

selectInput("p2_national_news",
         label = "Follow national news:",
         choices = c('Multiple times a day',
                     'Every day',
                     "Once a week",
                     "Hardly ever",
                     "Never"))



selectInput("p2_international_news",
         label = "Follow international news:",
         choices = c('Always',
                     "Sometimes",
                     "Never"))


selectInput("p2_news_medium",
         label = "Medium to follow news:",
         choices = c('TV',
                     'Print',
                     "Online",
                     "Social Media",
                     "Radio",
                     "Email newsletters",
                     "News app"))


selectInput("p2_follow_gov",
         label = "Follow government & public affairs:",
         choices = c('Most of the time',
                     'Some of the time',
                     "Only now and then",
                     "Hardly at all"))


selectInput("p2_travel_developing",
         label = "Travel to developing country:",
         choices = c('Yes', 'No'))



selectInput("p2_polical_pref",
         label = "Polical views from liberal to conservative:",
         choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p2_institution_trust",
         label = "Political institution trust from none to complete:",
         choices = c("0", '1', '2', '3','4','5','6','7'))



selectInput("p2_others_charitable",
         label = "People should be more charitable:",
         choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p2_worship_attendance",
         label = "Worship service attendance:",
         choices = c('Multiple times a week',
                     'Once a week',
                     "Once a month",
                     "Once a year",
                     "Never"))


selectInput("p2_religion_importance",
         label = "Importance of religion:",
         choices = c('Extremely important',
                     'Very important',
                     'Moderately important',
                     'Slightly important',
                     'Not at all important'))


selectInput("p2_religion",
         label = "Religion:",
         choices = c('Catholic',
                     'Protestant',
                     'Christian Orthodox',
                     'Jewish',
                     'Muslim',
                     'Sikh',
                     'Hindu',
                     'Buddhist',
                     'Atheist',
                     'Other'))


selectInput("p2_charity_importance",
          label = "Charity Importance:",
          choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p2_trust_in_charity",
            label = "Charity Trust:",
            choices = c("0", '1', '2', '3','4','5','6','7'))



selectInput("p2_donation_frequency",
         label = "Donation Frequency:",
         choices = c('Once a week',
                     'Once a Month',
                     'Once every three months',
                     'Once every six months',
                     'Once a year',
                     'Once every few years',
                     'Never'))



selectInput("p2_donation_amount",
         label = "Donation Amount:",
         choices = c("$1-$49",
                     '$50-$99',
                     '$100-$499',
                     '$500-$999',
                     '$1,000-$4,999',
                     '$5,000-$9,999',
                     '$10,000+'))


selectInput("p2_volunteer_12",
         label = "Volunteered in last 12 Months:",
         choices = c("Yes", "No"))



selectInput("p2_volunteer_frequency",
         label = "Volunteer Frequency:",
         choices = c('Once a week',
                     'Once a Month',
                     'Once every three months',
                     'Once every six months',
                     'Once a year',
                     'Once every few years',
                     'Never'))


selectInput("p2_personal_activism",
         label = "Personal Activism:",
         choices = c('Extremely involved',
                     'Very involved',
                     'Moderately involved',
                     'Slightly involved',
                     'Never involved'))


selectInput("p2_family_activism",
         label = "Family Activism:",
         choices = c('Extremely involved',
                     'Very involved',
                     'Moderately involved',
                     'Slightly involved',
                     'Never involved'))


selectInput("p2_religious_member",
         label = "Church Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p2_sport_member",
         label = "Sport or Recreational Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p2_art_member",
         label = "Art, Music, or Educational Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p2_labor_member",
         label = "Labor Union Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p2_political_member",
         label = "Political Party Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p2_environmental_member",
         label = "Enviornmental Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p2_professional_member",
         label = "Professional Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p2_humanitarian_member",
         label = "Humanitarian Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p2_consumer_member",
         label = "Consumer Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p2_other_member",
         label = "Other Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p2_gender",
         label = "Gender:",
         choices = c("Male",
                     "Female",
                     "Transgender",
                     "Prefer not to say",
                     "Other"))


selectInput("p2_marital_status",
         label = "Marital Status:",
         choices = c("Married",
                     "Widowed",
                     "Divorced",
                     "Separated",
                     "Never married"))


selectInput("p2_education",
         label = "Education:",
         choices = c("Less than high school",
                     "High school",
                     "Some college",
                     "2 year degree",
                     "4 year degree",
                     "Graduate degree",
                     "Doctorate"))

selectInput("p2_income",
         label = "Income:",
         choices = c('Less than $10,000',
                     '$10,000 to $19,999',
                     '$20,000 to $29,999',
                     '$30,000 to $39,999',
                     '$40,000 to $49,999',
                     '$50,000 to $59,999',
                     '$60,000 to $69,999',
                     '$70,000 to $79,999',
                     '$80,000 to $89,999',
                     '$90,000 to $99,999',
                     '$100,000 to $149,999',
                     '$150,000 to $199,999',
                     '$200,000 to $299,999',
                     '$300,000 or more'))


selectInput("p2_race",
         label = "Race(s):",
         choices = c('White',
                     'Black or African American',
                     'American Indian or Alaska Native',
                     'Asian',
                     'Native Hawaiian or Pacific Islander',
                     'Other'),
         multiple = TRUE)


selectInput("p2_age",
         label = "Age:",
         choices = c('Under 18',
                     '18 - 24',
                     '25 - 34',
                     '35 - 44',
                     '45 - 54',
                     '55 - 64',
                     '65 - 74',
                     '75 - 84',
                     '85 or older'))


```

### Persona 3

```{r persona 3 inputs}


# selectInput("model_choice",
#             label = "Select Model:",
#             choices = c("public_political_social_charity_demo"))


selectInput("p3_national_news",
         label = "Follow national news:",
         choices = c('Multiple times a day',
                     'Every day',
                     "Once a week",
                     "Hardly ever",
                     "Never"))


selectInput("p3_international_news",
         label = "Follow international news:",
         choices = c('Always',
                     "Sometimes",
                     "Never"))


selectInput("p3_news_medium",
         label = "Medium to follow news:",
         choices = c('TV',
                     'Print',
                     "Online",
                     "Social Media",
                     "Radio",
                     "Email newsletters",
                     "News app"))

selectInput("p3_follow_gov",
         label = "Follow government & public affairs:",
         choices = c('Most of the time',
                     'Some of the time',
                     "Only now and then",
                     "Hardly at all"))


selectInput("p3_travel_developing",
         label = "Travel to developing country:",
         choices = c('Yes', 'No'))



selectInput("p3_polical_pref",
         label = "Polical views from liberal to conservative:",
         choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p3_institution_trust",
         label = "Political institution trust from none to complete:",
         choices = c("0", '1', '2', '3','4','5','6','7'))



selectInput("p3_others_charitable",
         label = "People should be more charitable:",
         choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p3_worship_attendance",
         label = "Worship service attendance:",
         choices = c('Multiple times a week',
                     'Once a week',
                     "Once a month",
                     "Once a year",
                     "Never"))


selectInput("p3_religion_importance",
         label = "Importance of religion:",
         choices = c('Extremely important',
                     'Very important',
                     'Moderately important',
                     'Slightly important',
                     'Not at all important'))


selectInput("p3_religion",
         label = "Religion:",
         choices = c('Catholic',
                     'Protestant',
                     'Christian Orthodox',
                     'Jewish',
                     'Muslim',
                     'Sikh',
                     'Hindu',
                     'Buddhist',
                     'Atheist',
                     'Other'))


selectInput("p3_charity_importance",
          label = "Charity Importance:",
          choices = c("0", '1', '2', '3','4','5','6','7'))


selectInput("p3_trust_in_charity",
            label = "Charity Trust:",
            choices = c("0", '1', '2', '3','4','5','6','7'))



selectInput("p3_donation_frequency",
         label = "Donation Frequency:",
         choices = c('Once a week',
                     'Once a Month',
                     'Once every three months',
                     'Once every six months',
                     'Once a year',
                     'Once every few years',
                     'Never'))



selectInput("p3_donation_amount",
         label = "Donation Amount:",
         choices = c("$1-$49",
                     '$50-$99',
                     '$100-$499',
                     '$500-$999',
                     '$1,000-$4,999',
                     '$5,000-$9,999',
                     '$10,000+'))


selectInput("p3_volunteer_12",
         label = "Volunteered in last 12 Months:",
         choices = c("Yes", "No"))



selectInput("p3_volunteer_frequency",
         label = "Volunteer Frequency:",
         choices = c('Once a week',
                     'Once a Month',
                     'Once every three months',
                     'Once every six months',
                     'Once a year',
                     'Once every few years',
                     'Never'))


selectInput("p3_personal_activism",
         label = "Personal Activism:",
         choices = c('Extremely involved',
                     'Very involved',
                     'Moderately involved',
                     'Slightly involved',
                     'Never involved'))


selectInput("p3_family_activism",
         label = "Family Activism:",
         choices = c('Extremely involved',
                     'Very involved',
                     'Moderately involved',
                     'Slightly involved',
                     'Never involved'))


selectInput("p3_religious_member",
         label = "Church Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p3_sport_member",
         label = "Sport or Recreational Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p3_art_member",
         label = "Art, Music, or Educational Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p3_labor_member",
         label = "Labor Union Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p3_political_member",
         label = "Political Party Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p3_environmental_member",
         label = "Enviornmental Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p3_professional_member",
         label = "Professional Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p3_humanitarian_member",
         label = "Humanitarian Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p3_consumer_member",
         label = "Consumer Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))



selectInput("p3_other_member",
         label = "Other Org. Membership:",
         choices = c('Active Member',
                     'Inactive Member',
                     "Don't belong"))


selectInput("p3_gender",
         label = "Gender:",
         choices = c("Male",
                     "Female",
                     "Transgender",
                     "Prefer not to say",
                     "Other"))


selectInput("p3_marital_status",
         label = "Marital Status:",
         choices = c("Married",
                     "Widowed",
                     "Divorced",
                     "Separated",
                     "Never married"))


selectInput("p3_education",
         label = "Education:",
         choices = c("Less than high school",
                     "High school",
                     "Some college",
                     "2 year degree",
                     "4 year degree",
                     "Graduate degree",
                     "Doctorate"))

selectInput("p3_income",
         label = "Income:",
         choices = c('Less than $10,000',
                     '$10,000 to $19,999',
                     '$20,000 to $29,999',
                     '$30,000 to $39,999',
                     '$40,000 to $49,999',
                     '$50,000 to $59,999',
                     '$60,000 to $69,999',
                     '$70,000 to $79,999',
                     '$80,000 to $89,999',
                     '$90,000 to $99,999',
                     '$100,000 to $149,999',
                     '$150,000 to $199,999',
                     '$200,000 to $299,999',
                     '$300,000 or more'))



selectInput("p3_race",
         label = "Race(s):",
         choices = c('White',
                     'Black or African American',
                     'American Indian or Alaska Native',
                     'Asian',
                     'Native Hawaiian or Pacific Islander',
                     'Other'),
         multiple = TRUE)


selectInput("p3_age",
         label = "Age:",
         choices = c('Under 18',
                     '18 - 24',
                     '25 - 34',
                     '35 - 44',
                     '45 - 54',
                     '55 - 64',
                     '65 - 74',
                     '75 - 84',
                     '85 or older'))


```

<!-- There is an issue of not being able to see the last selectInput options when drop down box appears -->



<!-- Persona 2 Page -->


<!-- Persona 2 {.tabset .tabset-fade} -->
<!-- -------------------------------------------------- -->

<!-- ### Market Share Persona 2 -->

<!-- ```{r plot persona 2} -->
<!-- renderPlotly({ -->
<!--   choice = df() -->

<!--   persona = p_beta2 # Choose the persona -->

<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2) -->

<!--   ai_rate <- round(100 * ai_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->
<!--   gp_rate <- round(100 * gp_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->
<!--   ox_rate <- round(100 * ox_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->
<!--   rc_rate <- round(100 * rc_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->

<!--   data <- c(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util, ai_rate, gp_rate, ox_rate, rc_rate) -->
<!--   df <- as.data.frame(matrix(data, 8, 1)) -->

<!--   df[,2] <- c("Amnesty International", "Greenpeace", "Oxfam", "Red Cross") -->
<!--   df[,3] <- c(rep("Utility", 4), rep("Market Share", 4)) -->
<!--   df[,4] <- rep(c("Persona 1","Persona 2", "Persona 3"), length.out = 8) -->
<!--   colnames(df) <- c('Value', 'Organization', "Type", "Persona") -->

<!--   ggplotly(df %>% filter(Type == "Market Share") %>%  -->
<!--              ggplot(aes(y = Value, x = Organization, fill = Organization)) + -->
<!--              geom_col() + -->
<!--              labs(x="") +  -->
<!--              scale_fill_manual(values = c( "#FFC30B", "#3fad48", "#006633", "#660000")) + -->
<!--              theme(legend.position = "none") + -->
<!--              facet_wrap(~Type) -->
<!--     ) -->
<!-- }) -->
<!-- ``` -->

<!-- ### Amnesty International Market Share -->

<!-- ```{r valuebox ai persona 2} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->

<!--   persona = p_beta2 # Choose the persona -->

<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2) -->

<!--   ai_rate <- round(100 * ai_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->

<!--   valueBox(ai_rate, -->
<!--            color = "#FFC30B", -->
<!--            icon = "fa-percent") -->
<!-- }) -->
<!-- ``` -->

<!-- ### Greenpeace Market Share -->

<!-- ```{r valuebox gp persona 2} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->

<!--   persona = p_beta2 # Choose the persona -->

<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2) -->

<!--   gp_rate <- round(100 * gp_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->

<!--   valueBox(gp_rate, -->
<!--            color = "#3fad48", -->
<!--            icon = "fa-percent") -->
<!-- }) -->
<!-- ``` -->

<!-- ### Oxfam Market Share -->

<!-- ```{r valuebox ox persona 2} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->

<!--   persona = p_beta2 # Choose the persona -->

<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2) -->

<!--   ox_rate <- round(100 * ox_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->

<!--   valueBox(ox_rate, -->
<!--            color = "#006633", -->
<!--            icon = "fa-percent") -->
<!-- }) -->
<!-- ``` -->

<!-- ### Redcross Market Share -->

<!-- ```{r valuebox rc persona 2} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->

<!--   persona = p_beta2 # Choose the persona -->

<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona)),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona)),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona)),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona)),2) -->

<!--   rc_rate <- round(100 * rc_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->

<!--   valueBox(rc_rate, -->
<!--            color = "#660000", -->
<!--            icon = "fa-percent") -->
<!-- }) -->
<!-- ``` -->

<!-- Organizational Inputs {.tabset .tabset-fade} -->
<!-- ------------------------------------- -->
<!-- ### Amnesty International Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("ai_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("ai_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("ai_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in financial accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("ai_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("ai_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->

<!-- ### Greenpeace Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("gp_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("gp_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("gp_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("gp_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("gp_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->


<!-- ### Oxfam Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("ox_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("ox_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("ox_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("ox_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("ox_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->

<!-- ### Red Cross Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("rc_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("rc_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("rc_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("rc_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("rc_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->



<!-- Persona 3 Page  -->



<!-- Persona 3 {.tabset .tabset-fade} -->
<!-- -------------------------------------------------- -->

<!-- ### Market Share Persona 3 -->
<!-- ```{r plot persona 3} -->
<!-- renderPlotly({ -->
<!--   choice = df() -->

<!--   persona = p_beta3 # Choose the persona -->

<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona[,1])),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona[,1])),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona[,1])),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona[,1])),2) -->

<!--   ai_rate <- round(100 * ai_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->
<!--   gp_rate <- round(100 * gp_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->
<!--   ox_rate <- round(100 * ox_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->
<!--   rc_rate <- round(100 * rc_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->

<!--   data <- c(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util, ai_rate, gp_rate, ox_rate, rc_rate) -->
<!--   df <- as.data.frame(matrix(data, 8, 1)) -->

<!--   df[,2] <- c("Amnesty International", "Greenpeace", "Oxfam", "Red Cross") -->
<!--   df[,3] <- c(rep("Utility", 4), rep("Market Share", 4)) -->
<!--   df[,4] <- rep(c("Persona 1","Persona 2", "Persona 3"), length.out = 8) -->
<!--   colnames(df) <- c('Value', 'Organization', "Type", "Persona") -->

<!--   ggplotly(df %>% filter(Type == "Market Share") %>%  -->
<!--              ggplot(aes(y = Value, x = Organization, fill = Organization)) + -->
<!--              geom_col() + -->
<!--              labs(x="") +  -->
<!--              scale_fill_manual(values = c( "#FFC30B", "#3fad48", "#006633", "#660000")) + -->
<!--              theme(legend.position = "none") + -->
<!--              facet_wrap(~Type) -->
<!--     ) -->
<!-- }) -->
<!-- ``` -->

<!-- ### Amnesty International Market Share -->

<!-- ```{r valuebox ai persona 3} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->

<!--   persona = p_beta3 # Choose the persona -->

<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona[,1])),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona[,1])),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona[,1])),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona[,1])),2) -->

<!--   ai_rate <- round(100 * ai_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->

<!--   valueBox(ai_rate, -->
<!--            color = "#FFC30B", -->
<!--            icon = "fa-percent") -->
<!-- }) -->
<!-- ``` -->

<!-- ### Greenpeace Market Share -->

<!-- ```{r valuebox gp persona 3} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->

<!--   persona = p_beta3 # Choose the persona -->

<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona[,1])),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona[,1])),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona[,1])),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona[,1])),2) -->

<!--   gp_rate <- round(100 * gp_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->

<!--   valueBox(gp_rate, -->
<!--            color = "#3fad48", -->
<!--            icon = "fa-percent") -->
<!-- }) -->
<!-- ``` -->

<!-- ### Oxfam Market Share -->

<!-- ```{r valuebox ox persona 3} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->

<!--   persona = p_beta3 # Choose the persona -->

<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona[,1])),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona[,1])),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona[,1])),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona[,1])),2) -->

<!--   ox_rate <- round(100 * ox_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->

<!--   valueBox(ox_rate, -->
<!--            color = "#006633", -->
<!--            icon = "fa-percent") -->
<!-- }) -->
<!-- ``` -->

<!-- ### Redcross Market Share -->

<!-- ```{r valuebox rc persona 3} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->

<!--   persona = p_beta3 # Choose the persona -->

<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(persona[,1])),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(persona[,1])),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(persona[,1])),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(persona[,1])),2) -->

<!--   rc_rate <- round(100 * rc_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->

<!--   valueBox(rc_rate, -->
<!--            color = "#660000", -->
<!--            icon = "fa-percent") -->
<!-- }) -->
<!-- ``` -->

<!-- Organizational Inputs {.tabset .tabset-fade} -->
<!-- ------------------------------------- -->
<!-- ### Amnesty International Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("ai_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("ai_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("ai_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in financial accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("ai_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("ai_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->

<!-- ### Greenpeace Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("gp_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("gp_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("gp_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("gp_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("gp_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->


<!-- ### Oxfam Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("ox_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("ox_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("ox_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("ox_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("ox_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->

<!-- ### Red Cross Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("rc_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("rc_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("rc_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("rc_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("rc_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->




<!-- Old Code from before is below this line It is just commented out  ( Cmd Shift C ) -->



<!-- Organization Utility -->
<!-- ------------------------------------- -->
<!-- ## Amnesty International Expected Utility -->

<!-- ```{r} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->
<!--   ai_exp_util <- round(exp(t(choice[,3]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   valueBox(ai_exp_util, -->
<!--            color = "#FFC30B") -->
<!-- }) -->
<!-- ``` -->

<!-- ## Greenpeace Expected Utility -->

<!-- ```{r} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->
<!--   gp_exp_util <- round(exp(t(choice[,4]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   valueBox(gp_exp_util, -->
<!--            color = "#3fad48") -->
<!-- }) -->
<!-- ``` -->

<!-- ## Oxfam Expected Utility -->

<!-- ```{r} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->
<!--   ox_exp_util <- round(exp(t(choice[,5]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   valueBox(ox_exp_util, -->
<!--            color = "#006633") -->
<!-- }) -->
<!-- ``` -->

<!-- ## Redcross Expected Utility -->

<!-- ```{r} -->
<!-- renderValueBox({ -->
<!--   choice = df() -->
<!--   rc_exp_util <- round(exp(t(choice[,6]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   valueBox(rc_exp_util, -->
<!--            color = "#660000") -->
<!-- }) -->
<!-- ``` -->

<!-- Expected Donors {.tabset .tabset-fade} -->
<!-- ------------------------------------- -->
<!-- ### Amnesty International Expected Donors -->

<!-- ```{r echo=FALSE} -->
<!-- renderGauge({ -->
<!--   choice = df() -->
<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->

<!--   ai_rate <- round(100 * ai_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->
<!--   gauge(ai_rate, -->
<!--         min = 0, -->
<!--         max = 100, -->
<!--         gaugeSectors(colors = "#FFC30B"), -->
<!--         symbol = "%") -->
<!-- }) -->
<!-- ``` -->

<!-- ### Greenpeace Expected Donors -->

<!-- ```{r echo=FALSE} -->
<!-- renderGauge({ -->
<!--   choice = df() -->
<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->

<!--   gp_rate <- round(100 * gp_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->
<!--   gauge(gp_rate,  -->
<!--         min = 0,  -->
<!--         max = 100, -->
<!--         gaugeSectors(colors = "#3fad48"), -->
<!--         symbol = "%") -->
<!-- }) -->
<!-- ``` -->

<!-- ### Oxfam Expected Donors -->

<!-- ```{r echo=FALSE} -->
<!-- renderGauge({ -->
<!--   choice = df() -->
<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->

<!--   ox_rate <- round(100 * ox_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->
<!--   gauge(ox_rate,  -->
<!--         min = 0,  -->
<!--         max = 100, -->
<!--         gaugeSectors(colors = "#006633"), -->
<!--         symbol = "%") -->
<!-- }) -->
<!-- ``` -->

<!-- ### Red Cross Expected Donors -->

<!-- ```{r echo=FALSE} -->
<!-- renderGauge({ -->
<!--   choice = df() -->
<!--   ai_exp_util <- round(exp(t(choice[, 3]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   gp_exp_util <- round(exp(t(choice[, 4]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   ox_exp_util <- round(exp(t(choice[, 5]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->
<!--   rc_exp_util <- round(exp(t(choice[, 6]) %*% as.matrix(public_political_social_charity_demo[,2])),2) -->

<!--   rc_rate <- round(100 * rc_exp_util/sum(ai_exp_util, gp_exp_util, ox_exp_util, rc_exp_util)) -->
<!--   gauge(rc_rate,  -->
<!--         min = 0,  -->
<!--         max = 100, -->
<!--         gaugeSectors(colors = "#660000"), -->
<!--         symbol = "%") -->
<!-- }) -->
<!-- ``` -->

<!-- Organizational Inputs {.tabset .tabset-fade} -->
<!-- ------------------------------------- -->
<!-- ### Amnesty International Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("ai_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("ai_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("ai_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in financial accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("ai_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("ai_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->

<!-- ### Greenpeace Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("gp_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("gp_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("gp_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("gp_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("gp_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->


<!-- ### Oxfam Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("ox_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("ox_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("ox_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("ox_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("ox_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->

<!-- ### Red Cross Inputs -->

<!-- ```{r echo=FALSE} -->
<!-- selectInput("rc_issue",  -->
<!--             label = "Select Issue Area:", -->
<!--             choices = c("Emergency response", -->
<!--                         "Environment", -->
<!--                         "Human rights", -->
<!--                         "Refugee relief")) -->

<!-- selectInput("rc_fin_trans", -->
<!--             label = "Select Financial transparency:", -->
<!--             choices = c("Doesn’t engage in transparency", -->
<!--                         "Engages in transparency")) -->

<!-- selectInput("rc_account", -->
<!--             label = "Select Financial Accountability:", -->
<!--             choices = c("Doesn’t engage in accountability", -->
<!--                         "Engages in financial accountability")) -->

<!-- selectInput("rc_funding", -->
<!--             label = "Select Funding source:", -->
<!--             choices = c("Many small private donations", -->
<!--                         "Handful of wealthy private donors", -->
<!--                         "Government Grants")) -->

<!-- selectInput("rc_gov_relat", -->
<!--             label = "Select Relationship with host government", -->
<!--             choices = c("Friendly relationship with government", -->
<!--                         "Criticized by government",  -->
<!--                         "Under government crackdown")) -->
<!-- ``` -->
